apiVersion: v1 
kind: ConfigMap
metadata:
    name: {{ .Release.Name }}-config-volumen
    namespace: default
data:
    departamentos: |-
    {{- range .Values.departamentos }}
    - {{ . }}
    {{- end }}